# clean: deletecsv
# 	cargo clean
# 	cd airone_derive;cargo clean;

# format:
# 	cargo +nightly fmt

# deletecsv:
# 	find . -type f -name "*.csv" -delete

# test: deletecsv
# 	cargo test

# .PHONY=clean format deletecsv test
