// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::deserialize::{self, FromSql, Queryable};
use diesel::pg::Pg;
use diesel::serialize::{self, Output, ToSql};
use diesel::sql_types::Text;
use std::io::Write;

#[derive(Queryable, Debug)]
pub struct Todo {
    pub id: i32,
    pub user_id: i32,
    pub title: String,
    pub description: Option<String>,
    pub status: TodoStatus,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub password: String,
    pub is_admin: bool,
    pub created_at: Option<NaiveDateTime>,
}

// Added
use diesel::deserialize::FromSqlRow;
use diesel::expression::AsExpression;
use diesel::sql_types;

#[derive(Debug, AsExpression, FromSqlRow)]
#[diesel(sql_type = Text)]
pub enum TodoStatus {
    Pending,
    Doing,
    Canceled,
    Done,
}
