# The build stage
FROM rust:1.79-slim-buster as builder

RUN apt-get update -y && \
  apt-get install -y pkg-config \
  libssl-dev

WORKDIR /workspace

# RUN USER=root cargo new --bin actix
# RUN USER=root cargo new --lib components
# WORKDIR /actix-web-server

COPY ./Cargo.toml ./Cargo.toml
COPY ./config/container.toml ./container.toml
COPY ./crates ./crates

RUN cargo build --features "openapi" --release


# Stage 2: Create a lightweight image to run the application
FROM debian:buster-slim
#FROM scratch
RUN apt-get update && apt install -y openssl

COPY --from=builder /workspace/target/release/actix /usr/local/bin/actix
COPY --from=builder /workspace/target/release/axumfw /usr/local/bin/axumfw
COPY --from=builder /workspace/container.toml /container.toml

# Run the application
EXPOSE 8080

# ENTRYPOINT ["/usr/local/bin/actix"]
# CMD ["container.toml"]
